version: "3.8"

services:
  foundry:
    image: plantuml/plantuml-server:jetty
    hostname: localhost
    init: true
    restart: "unless-stopped"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
