name: "[workflow] Build and Deploy"

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    name: Build and Deploy documentation site
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up prerequisites - node and yarn
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Deploy to Cloudflare Pages
        run: yarn wrangler pages deploy _site --project-name=johnnolan-dev --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
