on:
  workflow_call:
    secrets:
      SONARCLOUD_SECRET:
        required: true

jobs:
  publish_sonar_cloud:
    name: Publish Sonar Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_SECRET }}
